void handler(int sig);
void mute_all_leechers_except(int seeder,int exception);
void open_all_leechers(int seeder);
int leechers(int seeder);
void clean();
void print_help();
int create_pipe(int id);
int connect_nodes(char* command);
int disconnect_nodes(char* command);
int create_node(char* command);
int find_only_son(int seeder);
int inject_node(char* command);
int parse_command(char* command);
void main_parser();
